### ISSUE TITLE
Missmatch seaborn vs R?

### ISSUE THREAD

**Issue by ssardina** [ssardina-research/coverage-plots#1]
@nitinef , I am either missing something or is not matching the charts I do with seaborn:

![image](https://github.com/user-attachments/assets/b797e39e-8122-4f0b-b053-9dbe21bb0c59)

The 100% should be on the right side right?

Also the scatter points are not matching, something is wrong (seaborn or R)

_Originally posted by @ssardina in https://github.com/ssardina-research/cfond-asp-private/issues/41#issuecomment-2306286575_

**Comment by nitinef** [comment]
@ssardina please check with a fresh pull?

**Comment by ssardina** [comment]
Ohh great, much better now

Now the average CPU numbers are wrong in one of the two charts. They are the same but in the wrong places. I think the error must be in MY seaborn, I will check it:

![image](https://github.com/user-attachments/assets/28648149-5a17-4f23-ae33-da34949228e0)


See S2 has 1445 in the R version, but that number shows up under A1 in my script :laughing:

**Comment by ssardina** [comment]
Seems the seaborn is not plotting well the scattered points against the correct solver:

![image](https://github.com/user-attachments/assets/fde7b99f-77ae-4321-8693-adf75bfc3760)

This is plotted against S1 (instead of F1):

![image](https://github.com/user-attachments/assets/6ac481be-7837-4ec1-9f8c-48c74a7a495d)

**Comment by ssardina** [comment]
OK so after analysis with specific data `spiky-tireworld` domain and `A2` solver:

- Both have correct coverage %
- R has correct scatter points, Python has it wrong (in another solver)
- Python has correct cputime mean, R has it wrong (in another solver)

![image](https://github.com/user-attachments/assets/d4f4b289-89ea-49b1-a9f3-6c135f320403)


![image](https://github.com/user-attachments/assets/aad1e1e0-6e3b-408b-8dc7-a70cdf1c71ce)

**Comment by ssardina** [comment]
I have fixed the seaborn plot and improve its looks.

I confirm the scatter points are correctly placed now.

![image](https://github.com/user-attachments/assets/2b1954c5-4776-47c2-93bd-50871fb6e8b5)

**Comment by ssardina** [comment]
Fantastic @nitinef , great team-work. Now both Python and R match perfectly and I have verified numbers do correspond to tables (coverage + scatter points + cputime mean):

![image](https://github.com/user-attachments/assets/08c936c7-4ab2-4c50-8bf2-a8b8112117fb)
