### ISSUE TITLE
R plot: mean for unsolvable domains

### ISSUE THREAD

**Issue by ssardina** [ssardina-research/coverage-plots#2]
See mean for A3 and A4, despite having 0% coverage:

![image](https://github.com/user-attachments/assets/049aba03-3108-431b-806e-39ddfd68baa0)

Isn't the mean of cputtime only on solved instances?

**Comment by nitinef** [comment]
Found the culprit. The script as converting solver type to y-axis location to calculate the location of the mean label. Now it should display the mean at the correct solver location. 

<img width="277" alt="Screenshot 2024-08-24 at 10 34 13 AM" src="https://github.com/user-attachments/assets/5185eb12-acf4-4767-ad81-a7cf70e0ad22">

**Comment by ssardina** [comment]
Fantastic @nitinef , great team-work. Now both Python and R match perfectly and I have verified numbers do correspond to tables (coverage + scatter points + cputime mean):

![image](https://github.com/user-attachments/assets/08c936c7-4ab2-4c50-8bf2-a8b8112117fb)

Done, closing this and #1

**Comment by ssardina** [comment]
But wait @nitinef , you solved the actual label of cputime, which now for unsolvable instances there is no number, fine (A3 and A4). 

But see the bar for those colvers in R, it still goes half way to the right and says coverage 0%. The bar length itself should be the coverage right? why the 0% is not on the left side as in the Python version?

![image](https://github.com/user-attachments/assets/c0efdf54-fe51-4ebc-8561-fac21f84265d)


BTW, I think with the new coloring, the Python version is a bit closer to R. Still not as pretty but much closer I think.

**Comment by nitinef** [comment]
> But see the bar for those colvers in R, it still goes half way to the right and says coverage 0%. The bar length itself should be the coverage right? why the 0% is not on the left side as in the Python version?

I added the min distance for label as 50% of x-axis just for aesthetic reasons. It can be easily changed here: https://github.com/ssardina-research/coverage-plots/blob/main/plots.R#L71

**Comment by ssardina** [comment]
ahhh OK, good, not a bug then, great!  A bit weird but I understand why you would do it.

Good, thanks! we now have both systems correct and aligned! :clap:
